[package]
name = "lover"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8",  features = ["blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
ansi_term = "0.12.1"
toml = "0.8.19"
zip = "2.2.0"
dirs = "5.0.1"
